# This workflow is used for publishing the static GitHub pages site.
#
# Before triggering a release the `semver.txt` file should be updated in the
# relevant branch.
#
# When commiting the version change in `semver.txt` the commit message is
# important as it will be used for the release in GitHub.
#
# For an example commit browse to
# https://github.com/CycloneDX/cyclonedx-dotnet/commit/d110af854371374460430bb8438225a7d7a84274.
# 
# The resulting release is here
# https://github.com/CycloneDX/cyclonedx-dotnet/releases/tag/v1.0.0.
#
# Releases are triggered manually. This can be done by browsing to
# https://github.com/CycloneDX/cyclonedx-web-tool/actions?query=workflow%3ARelease
# and selecting "Run workflow". If releasing a patch for a previous version
# make sure the correct branch is selected. It will default to the default
# branch.
name: Release

on:
  push

jobs:
  docker:
    name: docker
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: cyclonedx-web-tool
      IMAGE_VERSION: 0.5.2

    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3.0.2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build image and push
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          push: false
          build-args:
            VERSION=${{ env.IMAGE_VERSION }}
          tags: |
            cyclonedx/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}
            cyclonedx/${{ env.IMAGE_NAME }}:latest